//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by cgsharp tool.
//     Do not edit this file, your changes will be overwritten.
//
//     ToolVersion:  0.1.0-dev.120
//     QueryName:    betalingstype
//     TemplateName: dataenum
//     SqlText:      SELECT BETALING_TYPE,BETALING_TYPE_TXT FROM Info.brfa.PA60_BETALING_TYPE ORDER BY BETALING_TYPE
//     QueriedAt:    01/13/2021 18:39:01 +01:00
// </auto-generated>
//------------------------------------------------------------------------------
namespace Brf.Domus.Models
{
    /// <summary>
    /// Betalingstype angiver om der er tale om afdrag, renter etc.
    /// </summary>
    public enum Betalingstype
    {
        /// <summary>
        /// Kurstabsfradrag
        /// </summary>
        B001,
        /// <summary>
        /// Låneafdrag
        /// </summary>
        B002,
        /// <summary>
        /// Lånebidrag
        /// </summary>
        B003,
        /// <summary>
        /// Lånerente
        /// </summary>
        B004,
        /// <summary>
        /// Låneydelse
        /// </summary>
        B005,
        /// <summary>
        /// Finansieringsafdrag
        /// </summary>
        B006,
        /// <summary>
        /// Finansieringsrente
        /// </summary>
        B007,
        /// <summary>
        /// Finansieringsydelse
        /// </summary>
        B008,
        /// <summary>
        /// Indekstillæg - lånehovedstol
        /// </summary>
        B009,
        /// <summary>
        /// Indekstillæg - lånerestgæld
        /// </summary>
        B010,
        /// <summary>
        /// Indekstillæg - finansieringshovedstol
        /// </summary>
        B011,
        /// <summary>
        /// Indekstillæg - finansieringsrestgæld
        /// </summary>
        B012,
        /// <summary>
        /// Minimum bidrag
        /// </summary>
        B013,
        /// <summary>
        /// L-Rente-VP
        /// </summary>
        B015,
        /// <summary>
        /// FI-Rente-VP
        /// </summary>
        B016,
        /// <summary>
        /// Præmie
        /// </summary>
        B017,
        /// <summary>
        /// Intet beløb
        /// </summary>
        B018,
        /// <summary>
        /// Afdragsbidrag-sats
        /// </summary>
        B019,
        /// <summary>
        /// Låne afdragskorrektion
        /// </summary>
        B020,
        /// <summary>
        /// Indfrielsesrente
        /// </summary>
        B021,
        /// <summary>
        /// Indfrielsesbidrag
        /// </summary>
        B022,
        /// <summary>
        /// Indfrielsesgenplaceringsrente
        /// </summary>
        B024,
        /// <summary>
        /// Indfrielses Funding rente
        /// </summary>
        B025,
        /// <summary>
        /// Ex. ord Indfr.fi-afdrag
        /// </summary>
        B026,
        /// <summary>
        /// Ex. ord Indfr.fi-afdrag HS
        /// </summary>
        B027,
        /// <summary>
        /// Ex.ord låneafdrag
        /// </summary>
        B028,
        /// <summary>
        /// Ex.ord låneafdrag HS
        /// </summary>
        B029,
        /// <summary>
        /// Ex.ord afdrag Kurstabsfr RG
        /// </summary>
        B030,
        /// <summary>
        /// Ex.ord afdrag Kurstabsfr HS
        /// </summary>
        B031,
        /// <summary>
        /// Opsigelsesfinansieringsrente
        /// </summary>
        B032,
        /// <summary>
        /// Opsigelses-fi-afdrag
        /// </summary>
        B033,
        /// <summary>
        /// Straksindfrielses-fi-afdrag
        /// </summary>
        B038,
        /// <summary>
        /// Tilbagebetalt Depositum
        /// </summary>
        B039,
        /// <summary>
        /// Tilbagebetalt max. depositum
        /// </summary>
        B040,
        /// <summary>
        /// Låne HKK-Hovedstol Påvirkning
        /// </summary>
        B041,
        /// <summary>
        /// Finansierings HKK-Hovedstol Påvirkning
        /// </summary>
        B042,
        /// <summary>
        /// Regulering af IE-lån
        /// </summary>
        B043,
        /// <summary>
        /// Terminsregulering
        /// </summary>
        B044,
        /// <summary>
        /// Obligationsregulering, sidste termin
        /// </summary>
        B045,
        /// <summary>
        /// Refinansiering
        /// </summary>
        B046,
        /// <summary>
        /// Nedskrivning af lånehovedstolen
        /// </summary>
        B047,
        /// <summary>
        /// Nedskrivning af finansieringshovedstol
        /// </summary>
        B048,
        /// <summary>
        /// Afskrivning fi-restgæld
        /// </summary>
        B049,
        /// <summary>
        /// Afskrivning l-restgælden
        /// </summary>
        B050,
        /// <summary>
        /// IJ- afdragsbidrag
        /// </summary>
        B052,
        /// <summary>
        /// Opsigelsesbidrag
        /// </summary>
        B053,
        /// <summary>
        /// Ops. Tilb. Depositum
        /// </summary>
        B054,
        /// <summary>
        /// Ops. Tilb. max. depositum
        /// </summary>
        B055,
        /// <summary>
        /// Ex. ord lånafdrag - lånsidestyret
        /// </summary>
        B056,
        /// <summary>
        /// Ex. ord FI-afdrag - lånsidestyret
        /// </summary>
        B057,
        /// <summary>
        /// Ex. ord lånafdrag - finans. sidestyret
        /// </summary>
        B058,
        /// <summary>
        /// Ex. ord FI-afdrag - finans. sidestyret
        /// </summary>
        B059,
        /// <summary>
        /// Ex.ord indfrielsesfinasieringstillæg
        /// </summary>
        B060,
        /// <summary>
        /// Ex.ord indfrielsesafdrag VP
        /// </summary>
        B061,
        /// <summary>
        /// Ejerskifte lånerente
        /// </summary>
        B062,
        /// <summary>
        /// Ejerskifte finansierings rente
        /// </summary>
        B063,
        /// <summary>
        /// Indfrielsesafdragsbidrag
        /// </summary>
        B064,
        /// <summary>
        /// Ex.ord. indf.afdrag indeks. låneh.stol
        /// </summary>
        B065,
        /// <summary>
        /// Ex.ord. indf. FI-afdrag ind. FI-h.stol
        /// </summary>
        B066,
        /// <summary>
        /// Straksrente
        /// </summary>
        B067,
        /// <summary>
        /// Straks bidrag
        /// </summary>
        B068,
        /// <summary>
        /// Straks afdragsbidrag
        /// </summary>
        B069,
        /// <summary>
        /// FI-afdrag Straks FI-Restgæld
        /// </summary>
        B070,
        /// <summary>
        /// FI-rente Straks FI-Restgæld
        /// </summary>
        B071,
        /// <summary>
        /// FI-straks afdrag straks FI-Restgæld
        /// </summary>
        B072,
        /// <summary>
        /// Indf Pseudo Påvirk Kurstabsfradrag
        /// </summary>
        B073,
        /// <summary>
        /// Indfrielses kurstabsfradrag
        /// </summary>
        B074,
        /// <summary>
        /// Indfrielses HKK-depositum
        /// </summary>
        B075,
        /// <summary>
        /// Indfrielses max. opkrævet HKK depositum
        /// </summary>
        B076,
        /// <summary>
        /// Indfrielses HKK lånehovedstol
        /// </summary>
        B077,
        /// <summary>
        /// Indfrielses HKK finansierings hovedstol
        /// </summary>
        B078,
        /// <summary>
        /// Indfrielses beregningstal
        /// </summary>
        B079,
        /// <summary>
        /// Indfrielses bidrag-grundlag
        /// </summary>
        B080,
        /// <summary>
        /// FI-rente Straks FI-Restgæld VP
        /// </summary>
        B081,
        /// <summary>
        /// Ejerskifteafdrag på lånerestgæld
        /// </summary>
        B082,
        /// <summary>
        /// Ejerskifteafdrag på FI-restgælden
        /// </summary>
        B083,
        /// <summary>
        /// Ejerskifteafdrag på lånehovedstolen
        /// </summary>
        B084,
        /// <summary>
        /// Ejerskifteafdrag på FI-hovedstolen
        /// </summary>
        B085,
        /// <summary>
        /// Refinansiering FI-restgæld
        /// </summary>
        B086,
        /// <summary>
        /// Indfrielses VP rente
        /// </summary>
        B087,
        /// <summary>
        /// Opsigelses VP rente
        /// </summary>
        B088,
        /// <summary>
        /// Indf Pseudo Påvirk Låneafdrag
        /// </summary>
        B089,
        /// <summary>
        /// Indf Pseudo Påvirk Finansieringsafdrag
        /// </summary>
        B090,
        /// <summary>
        /// Indf Pseudo Påvirk Indx Till LåneHstol
        /// </summary>
        B091,
        /// <summary>
        /// Indf Pseudo Påvirk Indx Till LåneRstgæld
        /// </summary>
        B092,
        /// <summary>
        /// Indf Pseudo Påvirk Indx Till Fin.Hstol
        /// </summary>
        B093,
        /// <summary>
        /// Indf Pseudo Påvirk Indx Till Fin.Rstgæld
        /// </summary>
        B094,
        /// <summary>
        /// Indf Pseudo Påvirk Depositum
        /// </summary>
        B095,
        /// <summary>
        /// Indf Pseudo Påvirk Max. Depositum
        /// </summary>
        B096,
        /// <summary>
        /// Indf Pseudo Påvirk Obligationsregulering
        /// </summary>
        B097,
        /// <summary>
        /// Indf Pseudo Påvirk RTL Finans.afskriv
        /// </summary>
        B098,
        /// <summary>
        /// Indf Pseudo Påvirk RTL Låneafskriv
        /// </summary>
        B099,
        /// <summary>
        /// Indf Pseudo Påvirk IJ Afdragsbidrag
        /// </summary>
        B100,
        /// <summary>
        /// Indf Pseudo Påvirk Afdrag Lånesidest
        /// </summary>
        B101,
        /// <summary>
        /// Indf Pseudo Påvirk Fi Afdrag Lånesidest
        /// </summary>
        B102,
        /// <summary>
        /// Indf Pseudo Påvirk Afdrag Finanssidest
        /// </summary>
        B103,
        /// <summary>
        /// Indf Pseudo Påvirk Fi Afdrg Finanssidest
        /// </summary>
        B104,
        /// <summary>
        /// Indf Pseudo Påvirk Indekstillæg Brgnstal
        /// </summary>
        B105,
        /// <summary>
        /// Indf Indeks Tillæg Finansieringsrestgæld
        /// </summary>
        B106,
        /// <summary>
        /// Ops Indeks Tillæg Finansieringsrestgæld
        /// </summary>
        B107,
        /// <summary>
        /// Straks Indeks Tillæg Finans restgæld
        /// </summary>
        B108,
        /// <summary>
        /// Indeks tillæg til beregninsgtal
        /// </summary>
        B109,
        /// <summary>
        /// Straks Afdragsbidrag
        /// </summary>
        B110,
        /// <summary>
        /// Indeks tillæg til beregninsgtal-GI
        /// </summary>
        B111,
        /// <summary>
        /// Indeks tillæg til beregninsgtal-Stat
        /// </summary>
        B112,
        /// <summary>
        /// Indeks tillæg til beregninsgtal-Stat-5-8
        /// </summary>
        B113,
        /// <summary>
        /// Opdel-Kurstabs-HS
        /// </summary>
        B114,
        /// <summary>
        /// Opdel-Kurstabs-RG
        /// </summary>
        B115,
        /// <summary>
        /// Opdel-Lånehovedstol
        /// </summary>
        B116,
        /// <summary>
        /// Opdel-Lånerestgæld
        /// </summary>
        B117,
        /// <summary>
        /// Opdel-Indeks. Låne-HS
        /// </summary>
        B118,
        /// <summary>
        /// Opdel-Finansierings-HS
        /// </summary>
        B119,
        /// <summary>
        /// Opdel-Finansierings-RG
        /// </summary>
        B120,
        /// <summary>
        /// Opdel-Indeks. Finansierings-HS
        /// </summary>
        B121,
        /// <summary>
        /// Opdel-Finansierings VP-beløb
        /// </summary>
        B122,
        /// <summary>
        /// Opdel-Indbetalt HKK-depositum
        /// </summary>
        B123,
        /// <summary>
        /// Opdel-Max-opkrævning HKK-depositum
        /// </summary>
        B124,
        /// <summary>
        /// Opdel-HKK Lånehovedstol
        /// </summary>
        B125,
        /// <summary>
        /// Opdel-HKK Fi-hovedstol
        /// </summary>
        B126,
        /// <summary>
        /// Opdel-StraksindfrielsesFi-restgæld
        /// </summary>
        B127,
        /// <summary>
        /// Opdel-Beregningstal
        /// </summary>
        B128,
        /// <summary>
        /// Opdel-Restterminer
        /// </summary>
        B129,
        /// <summary>
        /// Opdel-IE Reguleringssaldo
        /// </summary>
        B130,
        /// <summary>
        /// Opdel-Bidrag-grundlag
        /// </summary>
        B131,
        /// <summary>
        /// Opdel-Beregntal-Stat-5-8
        /// </summary>
        B132,
        /// <summary>
        /// Opdel-Fi-RG-Indekstillæg
        /// </summary>
        B133,
        /// <summary>
        /// Opdel-Beregntal-Stat
        /// </summary>
        B134,
        /// <summary>
        /// Opdel-Beregntal-GI
        /// </summary>
        B135,
        /// <summary>
        /// Ekstraordinært afdrag beregningstal
        /// </summary>
        B136,
        /// <summary>
        /// Ekstraordinært afdrag bidrag grundlag
        /// </summary>
        B137,
        /// <summary>
        /// Ekstraordinært afdrag IE reg.saldo
        /// </summary>
        B138,
        /// <summary>
        /// Ekstraordinært afdrag restterminer
        /// </summary>
        B139,
        /// <summary>
        /// Ekstraordinært afdrag beregningstal stat
        /// </summary>
        B140,
        /// <summary>
        /// Ekstraordinært afdrag beregningstal GI
        /// </summary>
        B141,
        /// <summary>
        /// Ekstraordinært afdrag brgn.tal stat 5-8
        /// </summary>
        B142,
        /// <summary>
        /// Indf Omv Pseudo Ex.ord Kursfradrag HS
        /// </summary>
        B150,
        /// <summary>
        /// Indf Omv Pseudo Ex.ord Kurstabsfr RG
        /// </summary>
        B151,
        /// <summary>
        /// Indf Omv Pseudo Ex.ord låneafdrag HS
        /// </summary>
        B152,
        /// <summary>
        /// Indf Omv Pseudo Ex.ord låneafdrag RG
        /// </summary>
        B153,
        /// <summary>
        /// Indf Omv Pseudo Ex.ord. indf afd I HS
        /// </summary>
        B154,
        /// <summary>
        /// Indf Omv Pseudo Ex.ord Indf.fi-afd HS
        /// </summary>
        B155,
        /// <summary>
        /// Indf Omv Pseudo fi-afdrag
        /// </summary>
        B156,
        /// <summary>
        /// Indf Omv Pseudo Ex.ord FI-afd ind. FI-HS
        /// </summary>
        B157,
        /// <summary>
        /// Indf Omv Pseudo Ex.ord indf.afdrag VP
        /// </summary>
        B158,
        /// <summary>
        /// Indf Omv Pseudo Depositum
        /// </summary>
        B159,
        /// <summary>
        /// Indf Omv Pseudo Max. Depositum
        /// </summary>
        B160,
        /// <summary>
        /// Indf Omv Pseudo Indf HKK lånehovedstol
        /// </summary>
        B161,
        /// <summary>
        /// Indf Omv Pseudo Indf HKK fi hovedstol
        /// </summary>
        B162,
        /// <summary>
        /// Indf Omv Pseudo Indf beregningstal
        /// </summary>
        B163,
        /// <summary>
        /// Indf Omv Pseudo Indf bidrag-grundlag
        /// </summary>
        B164,
        /// <summary>
        /// Indf Omv Pseudo IT til beregntal-Stat
        /// </summary>
        B165,
        /// <summary>
        /// Indf Omv Pseudo IT til beregntal-GI
        /// </summary>
        B166,
        /// <summary>
        /// Indf Omv Pseudo IT beregntal-Stat-5-8 L
        /// </summary>
        B167,
        /// <summary>
        /// Konverteringsbesparelse
        /// </summary>
        B168,
        /// <summary>
        /// Skyggelån låneafdrag
        /// </summary>
        B169,
        /// <summary>
        /// Skyggelån lånerente
        /// </summary>
        B170,
        /// <summary>
        /// Skyggelån låneydelse
        /// </summary>
        B171,
        /// <summary>
        /// Udskudte afdrag
        /// </summary>
        B172,
        /// <summary>
        /// Nedskrivning af skygge lånerestgæld
        /// </summary>
        B173,
        /// <summary>
        /// Nedskrivning af skygge lånehovedstol
        /// </summary>
        B174,
        /// <summary>
        /// Nedskrivning af udskudt afdrag
        /// </summary>
        B175,
        /// <summary>
        /// Oprettelse af skygge hovedstol
        /// </summary>
        B176,
        /// <summary>
        /// Oprettelse af skygge lånerestgæld
        /// </summary>
        B177,
        /// <summary>
        /// Indf Pseudo Påvirk Skyg Låneafdrag
        /// </summary>
        B178,
        /// <summary>
        /// Indf Omv Pseudo Ex.ord Skyg låneafdr HS
        /// </summary>
        B179,
        /// <summary>
        /// Indf Omv Pseudo Ex.ord Skyg låneafdr RG
        /// </summary>
        B180,
        /// <summary>
        /// Indf Pseudo Påvirk Udskudt afdrag
        /// </summary>
        B181,
        /// <summary>
        /// Indf Omv Pseudo Ex.ord af Udsk afdra
        /// </summary>
        B182,
        /// <summary>
        /// Opdel skygge-lånehovedstol
        /// </summary>
        B183,
        /// <summary>
        /// Opdel skygge-lånerestgæld
        /// </summary>
        B184,
        /// <summary>
        /// Opdel udskudt afdrag
        /// </summary>
        B185,
        /// <summary>
        /// Kursskæring
        /// </summary>
        B186,
        /// <summary>
        /// Nedskrivning af kursskæringsrestgæld
        /// </summary>
        B187,
        /// <summary>
        /// Nedskrivning af kursskæringshovedstol
        /// </summary>
        B188,
        /// <summary>
        /// Indf Pseudo påvirk af kursskæring
        /// </summary>
        B189,
        /// <summary>
        /// Indf Omv Pseudo Ex.ord nedsk kursk HS
        /// </summary>
        B190,
        /// <summary>
        /// Indf Omv Pseudo Ex.ord nedsk kursk RG
        /// </summary>
        B191,
    }
}
