//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by cgsharp tool.
//     Do not edit this file, your changes will be overwritten.
//
//     ToolVersion:  0.1.0-dev.120
//     QueryName:    saldotype
//     TemplateName: dataenum
//     SqlText:      SELECT SALDO_TYPE,SALDO_TYPE_TXT FROM Info.brfa.PA70_SALDO_TYPE ORDER BY SALDO_TYPE
//     QueriedAt:    01/13/2021 18:39:10 +01:00
// </auto-generated>
//------------------------------------------------------------------------------
namespace Brf.Domus.Models
{
    /// <summary>
    /// Saldotype angiver om der er tale om restgaeld  etc.
    /// </summary>
    public enum Saldotype
    {
        /// <summary>
        /// Kurstabshovedstol
        /// </summary>
        S001,
        /// <summary>
        /// Kurstabsrestgæld
        /// </summary>
        S002,
        /// <summary>
        /// Lånehovedstol
        /// </summary>
        S003,
        /// <summary>
        /// Lånerestgæld
        /// </summary>
        S004,
        /// <summary>
        /// Indekseret lånehovedstol
        /// </summary>
        S005,
        /// <summary>
        /// Finansieringshovedstol
        /// </summary>
        S007,
        /// <summary>
        /// Finansieringsrestgæld
        /// </summary>
        S008,
        /// <summary>
        /// Indekseret finansieringshstol
        /// </summary>
        S009,
        /// <summary>
        /// Finansierings VP-beløb
        /// </summary>
        S011,
        /// <summary>
        /// Ingen saldo
        /// </summary>
        S012,
        /// <summary>
        /// Indbetalt HKK-depositum
        /// </summary>
        S022,
        /// <summary>
        /// Max-opkrævning HKK-depositum
        /// </summary>
        S023,
        /// <summary>
        /// HKK Lånehovedstol
        /// </summary>
        S024,
        /// <summary>
        /// HKK Fi-hovedstol
        /// </summary>
        S025,
        /// <summary>
        /// StraksindfrielsesFi-restgæld
        /// </summary>
        S026,
        /// <summary>
        /// Beregningstal
        /// </summary>
        S027,
        /// <summary>
        /// Bidrag - gundlag
        /// </summary>
        S031,
        /// <summary>
        /// IE Reguleringssaldo
        /// </summary>
        S032,
        /// <summary>
        /// Restterminer
        /// </summary>
        S037,
        /// <summary>
        /// Beregningstal - Stat
        /// </summary>
        S038,
        /// <summary>
        /// Beregningstal - GI
        /// </summary>
        S039,
        /// <summary>
        /// Beregningstal - Stat-5-8
        /// </summary>
        S040,
        /// <summary>
        /// Konverteringsbesparelse
        /// </summary>
        S041,
        /// <summary>
        /// Skyggelån hovedstol
        /// </summary>
        S042,
        /// <summary>
        /// Skyggelån restgæld
        /// </summary>
        S043,
        /// <summary>
        /// Udskudt afdrag
        /// </summary>
        S044,
        /// <summary>
        /// Debitors uindekserede egenbet.
        /// </summary>
        S045,
        /// <summary>
        /// Kursskæringshovedstol
        /// </summary>
        S046,
        /// <summary>
        /// Kursskæringsrestgæld
        /// </summary>
        S047,
        /// <summary>
        /// Bidragshovedstol
        /// </summary>
        S048,
        /// <summary>
        /// Kursværdi foranst. lån
        /// </summary>
        S049,
        /// <summary>
        /// Belåningsværdi
        /// </summary>
        S050,
    }
}
