namespace CSharpRazor
{
    public interface ICompiledTemplateDescriptor
    {
        /// <summary>
        /// The filename of the Razor template without the file extension.
        /// </summary>
        string TemplateName { get; }

        /// <summary>
        /// The filename of the Razor template, including the file extension.
        /// </summary>
        string TemplateFilename { get; }

        /// <summary>
        /// The fully qualified type name of the generated type, including its namespace but not its assembly.
        /// </summary>
        string TypeName { get; }

        /// <summary>
        /// The C# code generated by the <see cref="RazorCompiler"/> that for
        /// diagnostic purposes can be written to a file like '&lt;templateName&gt;.g.cshtml.cs'
        /// or somehow written to screen.
        /// </summary>
        string SourceCSharpCode { get; }
    }

    public interface IRenderedTemplateDescriptor : ICompiledTemplateDescriptor
    {
        /// <summary>
        /// The finished autogenerated content (i.e. C# code generated by the <see cref="RazorEngine"/>)
        /// </summary>
        string Content { get; }
    }
}
